favicon: /assets/img/favicon.png

### Site Settings ###
title               : Tilemachos Tsakiris
description         : >- 
                      IT Enthusiast | Projects & Portfolio
# baseurl             : ""                  # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          :   itstaftaf/itstaftaf.github.io  # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
# remote_theme: ""


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Tilemachos Tsakiris
  image             : /assets/img/profile.png
# behance           : your_username
# dribbble          : your_username
  email             : taf@tafstack.com
#  facebook          : your_username
  github            : itstaftaf
# gitlab            : your_username
  instagram         : its.taf_taf
# kaggle            : your_username
  linkedin          : tilemachos-t-4ba51ba3
#  medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : your_username
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username



### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
